name: App Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: build and test app
          run: |
              cd app
              npm install
              npm run test
              npm run build
        - name: deploy to netlify
          run: |
              npm install -g netlify-cli
              cd app
              netlify deploy --dir=./dist --prod


           
